<?php

namespace App\Providers;

use App\Events\ProductAdded;
use App\Listeners\NotifyAdminOfNewProductListener;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        ProductAdded::class => [
            NotifyAdminOfNewProductListener::class
        ]
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
